### PR TITLE
Remove verbosity to avoid cron email

### PR DESCRIPTION
**Pull request by filippocarletti**
I want to receive a mail only if there is a problem.
I do not want to see an email every month if things are working well.

https://github.com/NethServer/dev/issues/5617

### CODE REVIEW

**Review by stephdl — CHANGES_REQUESTED** [review]
testing your fix I found a new bug, please let me explain, it seems that get-oui and get-iab try to fetch an url with a symlink, and it fails to do it. This is what I have when I use the cron
```
 Could not get OUI data from http://standards.ieee.org/develop/regauth/oui/oui.txt
Could not get IAB data from http://standards.ieee.org/develop/regauth/iab/iab.txt
```
I propose to create a cron.monthly/UpdateArpScanVendors with 
```
#!/usr/bin/bash

cd /usr/share/arp-scan/
/usr/sbin/get-oui -u http://standards-oui.ieee.org/oui/oui.txt
/usr/sbin/get-iab -u http://standards-oui.ieee.org/iab/iab.txt
```
what do you think ?

**Comment by filippocarletti** [comment]
I also tested the script from cron and I never received the error above.
A google search returns the links you want to use (http://standards-oui.ieee.org/oui/)
Wikipedia has the links the script is using (http://standards.ieee.org/develop/regauth)
The arp-scan manual also has the Wikipedia link.

So, I'd prefer not to change the link.
BTW, we should discover why the download fails on your system.

**Comment by stephdl** [comment]
3 virtual servers under proxmox, I can reproduce
1 virtual server under virtualbox, I can reproduce

> BTW, we should discover why the download fails on your system.

:-?

**Comment by stephdl** [comment]
For reference
https://github.com/ianperrin/MMM-NetworkScanner/issues/27#issuecomment-386318198

**Comment by robbosch** [comment]
I have 2 servers without a problem and 1 with a problem as described by @stephdl 
Could it have to do with the servers having no problem are  configured as a gateway and the server that has the problem is not a gateway?

**Comment by stephdl** [comment]
I have myself a server with a gateway but with the error, however my gateway is a bit tricked, based on a dummy0 to protect the samba container.

A quick fix is my proposal :D

**Comment by robbosch** [comment]
My VPS is also with a dummy interface for green, but it has no problem. (subscribed ns7 with latest patches from subscription repo)

**Pull request merged**
